Provides required libraries for graphics capabilities
Summary:
The Monitoring Service plug-in, required to implement XEP-0313,
Message Archive Management, uses X11FontManager class, which
requires fontconfig to be available.

Fixes the following Java issue:
```
org.springframework.web.util.NestedServletException: Handler dispatch failed;
nested exception is java.lang.NoClassDefFoundError:
Could not initialize class sun.awt.X11FontManager
```

This is a follow-up for a5c611fc6f14.

Reference: https://stackoverflow.com/a/58765562/1930997

Test Plan:
Browse a statistic graph page:
https://xmpp.nasqueron.org/plugins/monitoring/graph?stat=server_sessions&sparkline=true&color=dark&format=png

Reviewers: dereckson

Reviewed By: dereckson

Differential Revision: https://devcentral.nasqueron.org/D2185